#include "pch.h"

__int64 XimAuthorityGetIsLocal_X() { return 0; }
__int64 XimAuthorityGetNetworkPathInformation_X() { return 0; }
__int64 XimAuthoritySendDataToPlayers_X() { return 0; }
__int64 XimAuthoritySetAuthorityReconciledData_X() { return 0; }
__int64 XimCleanup_X() { return 0; }
__int64 XimCreateOutOfBandReservation_X() { return 0; }
__int64 XimExtractProtocolActivationInformation_X() { return 0; }
__int64 XimFailFastWithInform_X() { return 0; }
__int64 XimFinishProcessingStateChanges_X() { return 0; }
__int64 XimGetAllowedPlayerJoins_X() { return 0; }
__int64 XimGetBackfillMatchmakingConfiguration_X() { return 0; }
__int64 XimGetChatTargets_X() { return 0; }
__int64 XimGetDebugMemoryMode_X() { return 0; }
__int64 XimGetMemFunctions_X() { return 0; }
__int64 XimGetNetworkCustomProperty_X() { return 0; }
__int64 XimGetPlayers_X() { return 0; }
__int64 XimGetThreadProcessor_X() { return 0; }
__int64 XimInitialize_X() { return 0; }
__int64 XimKickPlayer_X() { return 0; }
__int64 XimLeaveNetwork_X() { return 0; }
__int64 XimMoveToNetworkUsingJoinableXboxUserId_X() { return 0; }
__int64 XimMoveToNetworkUsingMatchmaking_X() { return 0; }
__int64 XimMoveToNetworkUsingOutOfBandReservation_X() { return 0; }
__int64 XimMoveToNetworkUsingProtocolActivatedEventArgs_X() { return 0; }
__int64 XimMoveToNewNetwork_X() { return 0; }
__int64 XimPlayerGetChatAudioRenderVolume_X() { return 0; }
__int64 XimPlayerGetChatIndicator_X() { return 0; }
__int64 XimPlayerGetChatMuted_X() { return 0; }
__int64 XimPlayerGetChatSpeechToTextConversionPreferenceEnabled_X() { return 0; }
__int64 XimPlayerGetChatTextToSpeechConversionPreferenceEnabled_X() { return 0; }
__int64 XimPlayerGetCustomPlayerContext_X() { return 0; }
__int64 XimPlayerGetCustomProperty_X() { return 0; }
__int64 XimPlayerGetGamertag_X() { return 0; }
__int64 XimPlayerGetIsLocal_X() { return 0; }
__int64 XimPlayerGetIsOnSameDeviceAsOtherPlayer_X() { return 0; }
__int64 XimPlayerGetMatchmakingConfiguration_X() { return 0; }
__int64 XimPlayerGetNetworkPathInformation_X() { return 0; }
__int64 XimPlayerGetTeamIndex_X() { return 0; }
__int64 XimPlayerGetWasMatchmade_X() { return 0; }
__int64 XimPlayerGetXboxUserId_X() { return 0; }
__int64 XimPlayerInviteUsers_X() { return 0; }
__int64 XimPlayerSendChatText_X() { return 0; }
__int64 XimPlayerSendDataToAuthority_X() { return 0; }
__int64 XimPlayerSendDataToOtherPlayers_X() { return 0; }
__int64 XimPlayerSetChatAudioRenderVolume_X() { return 0; }
__int64 XimPlayerSetChatMuted_X() { return 0; }
__int64 XimPlayerSetCustomPlayerContext_X() { return 0; }
__int64 XimPlayerSetCustomProperty_X() { return 0; }
__int64 XimPlayerSetMatchmakingConfiguration_X() { return 0; }
__int64 XimPlayerSetTeamIndex_X() { return 0; }
__int64 XimPlayerShowInviteUI_X() { return 0; }
__int64 XimRequestJoinableXboxUserIds_X() { return 0; }
__int64 XimSetAllowedPlayerJoins_X() { return 0; }
__int64 XimSetBackfillMatchmakingConfiguration_X() { return 0; }
__int64 XimSetChatTargets_X() { return 0; }
__int64 XimSetDebugMemoryMode_X() { return 0; }
__int64 XimSetIntendedLocalXboxUserIds_X() { return 0; }
__int64 XimSetMemFunctions_X() { return 0; }
__int64 XimSetNetworkCustomProperty_X() { return 0; }
__int64 XimSetThreadProcessor_X() { return 0; }
__int64 XimStartProcessingStateChanges_X() { return 0; }
