#pragma once
#include "Windows.Xbox.ApplicationModel.Store.Product.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Windows::Xbox::ApplicationModel::Store::implementation
{
    struct Product
    {
        Product() = default;

        static winrt::Windows::Foundation::IAsyncAction ShowPurchaseAsync(winrt::Windows::Xbox::System::IUser requestingUser, hstring offer);
        static winrt::Windows::Foundation::IAsyncAction ShowDetailsAsync(winrt::Windows::Xbox::System::IUser requestingUser, hstring productId);
        static winrt::Windows::Foundation::IAsyncAction ShowMarketplaceAsync(winrt::Windows::Xbox::System::IUser requestingUser, winrt::Windows::Xbox::ApplicationModel::Store::ProductItemTypes inputProductItemType, hstring inputProductId, winrt::Windows::Xbox::ApplicationModel::Store::ProductItemTypes resultProductItemTypes);
        static winrt::Windows::Foundation::IAsyncAction ShowRedeemCodeAsync(winrt::Windows::Xbox::System::IUser user, hstring offer);
        static winrt::Windows::Foundation::IAsyncAction ShowSubscriptionAsync(winrt::Windows::Xbox::System::IUser user, hstring productId, uint32_t privilegeId);
        static winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Xbox::ApplicationModel::Store::PrivilegeCheckResult> CheckPrivilegeAsync(winrt::Windows::Xbox::System::IUser user, uint32_t privilegeId, bool attemptResolution, hstring friendlyDisplay);
        static winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Xbox::ApplicationModel::Store::PrivilegeCheckResult> CheckPrivilegesAsync(winrt::Windows::Xbox::System::IUser user, winrt::Windows::Foundation::Collections::IVectorView<uint32_t> privilegeIds, bool attemptResolution, hstring friendlyDisplay);
        static winrt::event_token ProductPurchased(winrt::Windows::Xbox::ApplicationModel::Store::ProductPurchasedEventHandler const& handler);
        static void ProductPurchased(winrt::event_token const& token) noexcept;
        static winrt::Windows::Foundation::IAsyncAction ShowPurchaseForStoreIdAsync(winrt::Windows::Xbox::System::IUser requestingUser, hstring storeId);
        static winrt::Windows::Foundation::IAsyncAction ShowDetailsForStoreIdAsync(winrt::Windows::Xbox::System::IUser requestingUser, hstring storeId);
        static winrt::Windows::Foundation::IAsyncAction ShowUpsellAsync(winrt::Windows::Xbox::System::IUser requestingUser, uint32_t privilegeId, hstring prioritizedSku, uint32_t upsellEntryPoint, hstring referProductId);
        static winrt::Windows::Foundation::IAsyncAction ShowUpsellThirdPartyNoticeAsync(winrt::Windows::Xbox::System::IUser requestingUser);
    private:
        inline static winrt::event<winrt::Windows::Xbox::ApplicationModel::Store::ProductPurchasedEventHandler> m_productPurchasedEvent;
    };
}
namespace winrt::Windows::Xbox::ApplicationModel::Store::factory_implementation
{
    struct Product : ProductT<Product, implementation::Product>
    {
    };
}
