#include "pch.h"
#include "Windows.Xbox.Media.GameTransportControls.h"
#include "Windows.Xbox.Media.GameTransportControls.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Windows::Xbox::Media::implementation
{
    hstring GameTransportControls::Title()
    {
        return L"null";
    }
    hstring GameTransportControls::Subtitle()
    {
        return L"null";
    }
    winrt::Windows::Xbox::Media::GamePlaybackStatus GameTransportControls::PlaybackStatus()
    {
        return GamePlaybackStatus::Playing;
    }
    void GameTransportControls::PlaybackStatus(winrt::Windows::Xbox::Media::GamePlaybackStatus const& value)
    {
        // We ignore setting PlaybackStatus
    }
    winrt::Windows::Xbox::Media::SoundLevel GameTransportControls::SoundLevel()
    {
        return SoundLevel::Muted;
    }
    bool GameTransportControls::IsEnabled()
    {
        return false;
    }
    void GameTransportControls::IsEnabled(bool value)
    {
        // We ignore setting isEnabled
    }
    bool GameTransportControls::IsPlayEnabled()
    {
        return false;
    }
    void GameTransportControls::IsPlayEnabled(bool value)
    {
        // We ignore setting isPlayEnabled
    }
    bool GameTransportControls::IsPauseEnabled()
    {
        return false;
    }
    void GameTransportControls::IsPauseEnabled(bool value)
    {
        // We ignore setting IsPauseEnabled
    }
    bool GameTransportControls::IsMenuEnabled()
    {
        return false;
    }
    void GameTransportControls::IsMenuEnabled(bool value)
    {
        // We ignore setting IsMenuEnabled
    }
    bool GameTransportControls::IsViewEnabled()
    {
        return false;
    }
    void GameTransportControls::IsViewEnabled(bool value)
    {
        // We ignore setting IsViewEnabled
    }
    bool GameTransportControls::IsBackEnabled()
    {
        return false;
    }
    void GameTransportControls::IsBackEnabled(bool value)
    {
        // We ignore setting IsBackEnabled
    }
    winrt::event_token GameTransportControls::ButtonPressed(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Media::GameTransportControls, winrt::Windows::Xbox::Media::GameTransportControlsButtonPressedEventArgs> const& handler)
    {
        return m_gameTransportControlsButtonPressedEventArgs.add(handler);
    }
    void GameTransportControls::ButtonPressed(winrt::event_token const& token) noexcept
    {
        m_gameTransportControlsButtonPressedEventArgs.remove(token);
    }
    winrt::event_token GameTransportControls::PropertyChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Media::GameTransportControls, winrt::Windows::Xbox::Media::GameTransportControlsPropertyChangedEventArgs> const& handler)
    {
        return m_gameTransportControlsPropertyChangedEventArgs.add(handler);
    }
    void GameTransportControls::PropertyChanged(winrt::event_token const& token) noexcept
    {
        m_gameTransportControlsPropertyChangedEventArgs.remove(token);
    }
}
