#include "pch.h"
#include "Windows.Xbox.Management.Deployment.ContentLocation.h"
#include "Windows.Xbox.Management.Deployment.ContentLocation.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Windows::Xbox::Management::Deployment::implementation
{
    ContentLocation::ContentLocation(hstring const& path)
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Xbox::Management::Deployment::IContentInstallationInfo> ContentLocation::InstallationInfos()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::Management::Deployment::IContentMetadata ContentLocation::BundleMetadata()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::Management::Deployment::IContentInstallationInfo ContentLocation::DefaultInstallationInfo()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::Management::Deployment::ContentLocationContentType ContentLocation::ContentType()
    {
        throw hresult_not_implemented();
    }
    uint32_t ContentLocation::DiscNumber()
    {
        throw hresult_not_implemented();
    }
    uint32_t ContentLocation::DiscCount()
    {
        throw hresult_not_implemented();
    }
    hstring ContentLocation::DiscSetId()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::Collections::IVectorView<hstring> ContentLocation::PackageTitles()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Xbox::Management::Deployment::IContentInstallationInfo> ContentLocation::HiddenInstallationInfos()
    {
        throw hresult_not_implemented();
    }
}
