#include "pch.h"
#include "Windows.Xbox.Input.InputManager.h"
#include "Windows.Xbox.Input.InputManager.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Windows::Xbox::Input::implementation
{
    void InputManager::SetKinectOnePersonSystemEngagement()
    {
        throw hresult_not_implemented();
    }
    void InputManager::SetKinectTwoPersonSystemEngagement()
    {
        throw hresult_not_implemented();
    }
    void InputManager::SetKinectOnePersonManualEngagement(winrt::Windows::Xbox::Input::BodyHandPair const& bodyHandPair)
    {
        throw hresult_not_implemented();
    }
    void InputManager::SetKinectTwoPersonManualEngagement(winrt::Windows::Xbox::Input::BodyHandPair const& bodyHandPair1, winrt::Windows::Xbox::Input::BodyHandPair const& bodyHandPair2)
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Xbox::Input::BodyHandPair> InputManager::KinectManualEngagedHands()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::Input::KinectEngagementMode InputManager::KinectEngagementMode()
    {
        throw hresult_not_implemented();
    }
    uint32_t InputManager::MaximumKinectEngagedPersonCount()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::Input::SystemCursorVisibility InputManager::SystemCursorVisibility()
    {
        throw hresult_not_implemented();
    }
    void InputManager::SystemCursorVisibility(winrt::Windows::Xbox::Input::SystemCursorVisibility const& visibility)
    {
        throw hresult_not_implemented();
    }
    void InputManager::DeferSystemGestures()
    {
        throw hresult_not_implemented();
    }
    void InputManager::OverrideKinectInteractionMode(winrt::Windows::Xbox::Input::KinectInteractionMode const& mode)
    {
        throw hresult_not_implemented();
    }
    bool InputManager::DoesGamepadDeferKinectInteractions()
    {
        throw hresult_not_implemented();
    }
    void InputManager::DoesGamepadDeferKinectInteractions(bool doesGamepadDeferKinectInteractions)
    {
        throw hresult_not_implemented();
    }
    bool InputManager::IsKinectPersonEngaged()
    {
        throw hresult_not_implemented();
    }
    winrt::event_token InputManager::IsKinectPersonEngagedChanged(winrt::Windows::Foundation::EventHandler<winrt::Windows::Xbox::Input::IsKinectPersonEngagedChangedEventArgs> const& handler)
    {
        throw hresult_not_implemented();
    }
    void InputManager::IsKinectPersonEngagedChanged(winrt::event_token const& token) noexcept
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::Input::InputMode InputManager::SmartglassInputMode()
    {
        throw hresult_not_implemented();
    }
    void InputManager::SmartglassInputMode(winrt::Windows::Xbox::Input::InputMode const& mode)
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::Input::ManipulationMode InputManager::SmartglassManipulationModes()
    {
        throw hresult_not_implemented();
    }
    void InputManager::SmartglassManipulationModes(winrt::Windows::Xbox::Input::ManipulationMode const& mode)
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::Input::InputMode InputManager::GamepadInputMode()
    {
        throw hresult_not_implemented();
    }
    void InputManager::GamepadInputMode(winrt::Windows::Xbox::Input::InputMode const& mode)
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::Input::ManipulationMode InputManager::GamepadManipulationModes()
    {
        throw hresult_not_implemented();
    }
    void InputManager::GamepadManipulationModes(winrt::Windows::Xbox::Input::ManipulationMode const& mode)
    {
        throw hresult_not_implemented();
    }
}
