#pragma once
#include "Windows.Xbox.Management.Deployment.ContentLocation.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Windows::Xbox::Management::Deployment::implementation
{
    struct ContentLocation : ContentLocationT<ContentLocation>
    {
        ContentLocation() = default;

        ContentLocation(hstring const& path);
        winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Xbox::Management::Deployment::IContentInstallationInfo> InstallationInfos();
        winrt::Windows::Xbox::Management::Deployment::IContentMetadata BundleMetadata();
        winrt::Windows::Xbox::Management::Deployment::IContentInstallationInfo DefaultInstallationInfo();
        winrt::Windows::Xbox::Management::Deployment::ContentLocationContentType ContentType();
        uint32_t DiscNumber();
        uint32_t DiscCount();
        hstring DiscSetId();
        winrt::Windows::Foundation::Collections::IVectorView<hstring> PackageTitles();
        winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Xbox::Management::Deployment::IContentInstallationInfo> HiddenInstallationInfos();
    };
}
namespace winrt::Windows::Xbox::Management::Deployment::factory_implementation
{
    struct ContentLocation : ContentLocationT<ContentLocation, implementation::ContentLocation>
    {
    };
}
