#pragma once
#include "Windows.Xbox.CloudLanguageServices.CloudSpeechSession.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::CloudLanguageServices::implementation
{
    struct CloudSpeechSession : CloudSpeechSessionT<CloudSpeechSession>
    {
        CloudSpeechSession() = default;

        void NotifyConversationMessage(winrt::Windows::Xbox::CloudLanguageServices::IConversationMessage const& conversationMessage);
        void NotifyTransientMessage(winrt::Windows::Xbox::CloudLanguageServices::ITransientMessage const& transientMessage);
        void NotifyContextRequired();
        void NotifyConversationMessageRaw(hstring const& message);
        void NotifyTransientMessageRaw(hstring const& message);
        void SubmitTextQuery(hstring const& textQuery);
        void SubmitActionQuery(hstring const& actionQuery, hstring const& itemId);
        void set_Context(hstring const& contextDoc);
        void EnableContinuousReco();
        void DisableContinuousReco();
        winrt::event_token ConversationMessageArrived(winrt::Windows::Xbox::CloudLanguageServices::ConversationMessageHandler const& handler);
        void ConversationMessageArrived(winrt::event_token const& token) noexcept;
        winrt::event_token TransientMessageArrived(winrt::Windows::Xbox::CloudLanguageServices::TransientMessageHandler const& handler);
        void TransientMessageArrived(winrt::event_token const& token) noexcept;
        winrt::event_token CloudStreamingStateChanged(winrt::Windows::Xbox::CloudLanguageServices::CloudStreamingStateChangedHandler const& handler);
        void CloudStreamingStateChanged(winrt::event_token const& token) noexcept;
        winrt::event_token QueryingModeStateChanged(winrt::Windows::Xbox::CloudLanguageServices::QueryingModeStateChangedHandler const& handler);
        void QueryingModeStateChanged(winrt::event_token const& token) noexcept;
        winrt::event_token ContextRequired(winrt::Windows::Xbox::CloudLanguageServices::ContextRequiredHandler const& handler);
        void ContextRequired(winrt::event_token const& cookie) noexcept;
        winrt::event_token ConversationMessageErrorArrived(winrt::Windows::Xbox::CloudLanguageServices::ConversationMessageErrorHandler const& handler);
        void ConversationMessageErrorArrived(winrt::event_token const& token) noexcept;
    };
}
