#include "pch.h"
#include "Windows.Xbox.Cab.Internal.CabManager.h"
#include "Windows.Xbox.Cab.Internal.CabManager.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::Cab::Internal::implementation
{
    winrt::Windows::Foundation::IAsyncActionWithProgress<uint32_t> CabManager::CreateCabFileAsync(hstring cabFilePath, hstring sourceDirectory)
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::IAsyncActionWithProgress<uint32_t> CabManager::ExtractCabFileAsync(hstring cabFilePath, hstring targetPath)
    {
        throw hresult_not_implemented();
    }
    void CabManager::CreateCabFile(hstring const& cabFilePath, hstring const& sourceDirectory, winrt::Windows::Xbox::Cab::Internal::ReportProgressHandler const& cabManagerProgress)
    {
        throw hresult_not_implemented();
    }
    void CabManager::ExtractCabFile(hstring const& cabFilePath, hstring const& targetPath, winrt::Windows::Xbox::Cab::Internal::ReportProgressHandler const& cabManagerProgress)
    {
        throw hresult_not_implemented();
    }
}
