#include "pch.h"
#include "Windows.Xbox.Controls.NuiControl.NuiConfig.h"
#include "Windows.Xbox.Controls.NuiControl.NuiConfig.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::Controls::NuiControl::implementation
{
    hstring NuiConfig::KinectVersion()
    {
        throw hresult_not_implemented();
    }
    bool NuiConfig::IsKinectConnectedToCorrectPort()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::IAsyncOperationWithProgress<winrt::Windows::Xbox::Controls::NuiControl::INuiAudioTestResult, uint32_t> NuiConfig::RunNuiAudioTestAsync(winrt::Windows::Xbox::Controls::NuiControl::NuiAudioTest testToRun)
    {
        throw hresult_not_implemented();
    }
    int32_t NuiConfig::NA_E_CALIBRATE_DEADMIC()
    {
        throw hresult_not_implemented();
    }
    int32_t NuiConfig::NA_E_CALIBRATE_NOISELEVEL_TOOLOUD()
    {
        throw hresult_not_implemented();
    }
    int32_t NuiConfig::NA_E_CALIBRATE_SPKLEVEL_TOOLOUD()
    {
        throw hresult_not_implemented();
    }
    int32_t NuiConfig::NA_E_CALIBRATE_SPKLEVEL_TOOSOFT()
    {
        throw hresult_not_implemented();
    }
    int32_t NuiConfig::NA_S_CALIBRATE_OK()
    {
        throw hresult_not_implemented();
    }
}
