#pragma once
#include "Windows.Xbox.Media.SystemMediaTransportControlsDisplayUpdater.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::Media::implementation
{
    struct SystemMediaTransportControlsDisplayUpdater : SystemMediaTransportControlsDisplayUpdaterT<SystemMediaTransportControlsDisplayUpdater>
    {
        SystemMediaTransportControlsDisplayUpdater() = default;

        winrt::Windows::Xbox::Media::MediaPlaybackType Type();
        void Type(winrt::Windows::Xbox::Media::MediaPlaybackType const& value);
        hstring AppMediaId();
        void AppMediaId(hstring const& value);
        winrt::Windows::Storage::Streams::RandomAccessStreamReference Thumbnail();
        void Thumbnail(winrt::Windows::Storage::Streams::RandomAccessStreamReference const& value);
        winrt::Windows::Xbox::Media::MusicDisplayProperties MusicProperties();
        winrt::Windows::Xbox::Media::VideoDisplayProperties VideoProperties();
        winrt::Windows::Xbox::Media::ImageDisplayProperties ImageProperties();
        winrt::Windows::Xbox::Media::ConversationDisplayProperties ConversationProperties();
        winrt::Windows::Xbox::Media::GameDisplayProperties GameProperties();
        winrt::Windows::Foundation::IAsyncOperation<bool> CopyFromFileAsync(winrt::Windows::Xbox::Media::MediaPlaybackType type, winrt::Windows::Storage::StorageFile source);
        void ClearAll();
        void Update();
    };
}
