#pragma once
#include "Windows.Xbox.Safety.Internal.ParentalControls.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::Safety::Internal::implementation
{
    struct ParentalControls
    {
        ParentalControls() = default;

        static winrt::Windows::Foundation::IAsyncOperation<int32_t> RequestPermissionForAppIDAsync(hstring AppID, bool checkOnly);
        static winrt::Windows::Foundation::IAsyncOperation<int32_t> SetPinAsync(uint32_t consoleUserId, int32_t pin);
        static winrt::Windows::Foundation::IAsyncOperation<bool> CheckPinAsync(uint32_t consoleUserId, int32_t pin);
        static bool ShouldPromptPassKeyForSignIn(uint32_t consoleUserId);
        static winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Xbox::Safety::Internal::ParentApprovalSession> GetParentForApprovalAsync(winrt::Windows::Xbox::System::IUser child, hstring message);
        static winrt::Windows::Foundation::IAsyncOperation<bool> PromptAdultForSelfApprovalAsync(winrt::Windows::Xbox::System::IUser adult, hstring contentTitle);
        static winrt::Windows::Foundation::IAsyncOperation<uint32_t> GetBlurayRestrictionLevelAsync();
        static winrt::Windows::Foundation::IAsyncOperation<uint32_t> GetDVDRestrictionLevelAsync();
        static winrt::Windows::Foundation::IAsyncOperation<bool> RequestContentPurchaseAccessAsync(winrt::Windows::Xbox::System::IUser user, winrt::Windows::Media::ContentRestrictions::RatedContentDescription ratedContentDescription, bool isFree);
        static winrt::Windows::Foundation::IAsyncOperation<hstring> GetLiveContentFilterHeaderAsync();
        static winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Media::ContentRestrictions::ContentAccessRestrictionLevel> GetRestrictionLevelAsync(winrt::Windows::Xbox::System::IUser user, winrt::Windows::Media::ContentRestrictions::RatedContentDescription ratedContentDescription);
        static winrt::Windows::Foundation::IAsyncOperation<bool> CheckPasskeyForPurchaseAsync(winrt::Windows::Xbox::System::IUser user);
        static winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<hstring>> GetApprovableAdultsAsync(winrt::Windows::Xbox::System::IUser user);
        static winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Xbox::Safety::Internal::ParentApprovalSession> GetParentApprovalSessionFromAccountPickerResultAsync(winrt::Windows::Xbox::System::IUser child, winrt::Windows::Xbox::System::IUser selectedAdult, bool adultWasSignedIn);
        static winrt::Windows::Foundation::IAsyncOperation<bool> GetShouldObscureAdultTVListingsAsync();
        static bool CanUserSignInOverCurrentTitle(uint32_t consoleUserId);
        static bool DoesUserHavePasskey(uint32_t consoleUserId);
        static winrt::Windows::Foundation::IAsyncOperation<bool> RequestPromotionalContentAccessAsync(winrt::Windows::Media::ContentRestrictions::RatedContentDescription ratedContentDescription);
        static winrt::Windows::Foundation::IAsyncOperation<bool> CanUserAccessPromotionalContentAsync(uint32_t consoleUserId, winrt::Windows::Media::ContentRestrictions::RatedContentDescription ratedContentDescription);
        static winrt::hresult RequestPermissionForAppIDWithoutUI(hstring const& AppID);
        static winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Xbox::Safety::Internal::MUAPrivacyAppCheckItem>> GetUnapprovedMUAPrivacyAppsAsync(uint32_t consoleUserId);
        static void AddMUAPrivacyExemption(uint32_t consoleUserId, hstring const& AppID);
        static void ExtendScreenTimeLocally(uint32_t consoleUserId, uint32_t extensionTimeInMinutes);
        static void DisableCurrentScreenTimeLocally(uint32_t consoleUserId);
        static void GetUserNextScreenTimeLock(uint32_t consoleUserId, bool& hasLockTime, winrt::Windows::Foundation::DateTime& lockTime);
        static void SetUserNextScreenTimeLock(uint32_t consoleUserId, winrt::Windows::Foundation::DateTime const& lockTime);
        static void ClearUserNextScreenTimeLock(uint32_t consoleUserId);
        static winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Xbox::Safety::Internal::DevkitActivationRequestStatus> XDesActivationAsync(hstring consoleSerialNumber);
        static winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Xbox::Safety::Internal::ParentApprovalSession> GetParentForApprovalAsync(winrt::Windows::System::User child, hstring message);
        static winrt::Windows::Foundation::IAsyncOperation<bool> PromptAdultForSelfApprovalAsync(winrt::Windows::System::User adult, hstring contentTitle);
        static winrt::Windows::Foundation::IAsyncOperation<bool> RequestContentPurchaseAccessAsync(winrt::Windows::System::User user, winrt::Windows::Media::ContentRestrictions::RatedContentDescription ratedContentDescription, bool isFree);
        static winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Media::ContentRestrictions::ContentAccessRestrictionLevel> GetRestrictionLevelAsync(winrt::Windows::System::User user, winrt::Windows::Media::ContentRestrictions::RatedContentDescription ratedContentDescription);
        static winrt::Windows::Foundation::IAsyncOperation<bool> CheckPasskeyForPurchaseAsync(winrt::Windows::System::User user);
        static winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<hstring>> GetApprovableAdultsAsync(winrt::Windows::System::User user);
        static winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Xbox::Safety::Internal::ParentApprovalSession> GetParentApprovalSessionFromAccountPickerResultAsync(winrt::Windows::System::User child, winrt::Windows::System::User selectedAdult, bool adultWasSignedIn);
        static winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Xbox::Safety::Internal::LiveContentFilterHeader> GetLiveContentFilterHeaderDataAsync();
        static winrt::Windows::Foundation::IAsyncOperation<bool> RequestBrowsePermissionForRatedContentAsync(winrt::Windows::Media::ContentRestrictions::RatedContentDescription ratedContentDescription, bool checkOnly);
        static winrt::Windows::Foundation::IAsyncOperation<bool> RequestPermissionForContentAsync(winrt::Windows::Media::ContentRestrictions::RatedContentDescription ratedContentDescription, winrt::Windows::Media::ContentRestrictions::RatedContentDescription parentRatedContentDescription, bool checkOnly);
        static winrt::Windows::Foundation::Collections::IVectorView<hstring> GetRatingBoardsByPriority(hstring const& region, winrt::Windows::Media::ContentRestrictions::RatedContentCategory const& category);
        static void OverrideMaturityLevels(uint32_t blockMaturityLevel, uint32_t warnMaturityLevel, bool canViewBlockedContent);
        static void OverrideUserMaturityLevel(winrt::Windows::Xbox::System::IUser const& user, uint32_t maturityLevel, bool canViewBlockedContent);
        static void OverridePin(int32_t userPin);
        static void OverrideAppContentDescription(winrt::Windows::Media::ContentRestrictions::RatedContentDescription const& contentItemDescription);
        static void ClearAllTestSettings();
        static void TriggerRestrictionsChangedEvent();
        static bool CanDisplayPromotionalContent(winrt::Windows::Media::ContentRestrictions::RatedContentDescription const& ratedContentDescription);
        static void OverrideUserMaturityLevel(winrt::Windows::System::User const& user, uint32_t maturityLevel, bool canViewBlockedContent);
        static winrt::event_token AppTimerTestEvent(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Foundation::IInspectable, winrt::Windows::Foundation::IInspectable> const& handler);
        static void AppTimerTestEvent(winrt::event_token const& token) noexcept;
        static void FireAppTimerTestEvent(winrt::Windows::Xbox::Safety::Internal::AppTimerTestEventType const& eventType, uint32_t consoleUserId, hstring const& appId, uint32_t reason, winrt::Windows::Foundation::DateTime const& nextLockOrUnlockTime, uint32_t nextLockReason, winrt::Windows::Foundation::TimeSpan const& timeLeft, winrt::Windows::Foundation::TimeSpan const& warningThreshold);
    };
}
namespace winrt::Windows::Xbox::Safety::Internal::factory_implementation
{
    struct ParentalControls : ParentalControlsT<ParentalControls, implementation::ParentalControls>
    {
    };
}
