#pragma once
#include "Windows.Xbox.Safety.Internal.ConsoleSettings.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::Safety::Internal::implementation
{
    struct ConsoleSettings
    {
        ConsoleSettings() = default;

        static void Enabled(bool value);
        static bool Enabled();
        static void MaturityLevel(uint32_t value);
        static uint32_t MaturityLevel();
        static void CanBrowseContentAboveMaturityLevel(bool value);
        static bool CanBrowseContentAboveMaturityLevel();
        static void AllowNewProfiles(bool value);
        static bool AllowNewProfiles();
        static bool IsPassKeySet();
        static void ClearPassKey();
        static void ObscureAdultTVListings(bool value);
        static bool ObscureAdultTVListings();
        static void AllowGuestUsers(bool value);
        static bool AllowGuestUsers();
        static void AllowFactoryReset(bool value);
        static bool AllowFactoryReset();
        static void AllowDeleteProfiles(bool value);
        static bool AllowDeleteProfiles();
        static void AllowChangeRegion(bool value);
        static bool AllowChangeRegion();
        static void DeleteProfilesOnSignOut(bool value);
        static bool DeleteProfilesOnSignOut();
        static void AllowBrowser(bool value);
        static bool AllowBrowser();
        static void AllowInstallApps(bool value);
        static bool AllowInstallApps();
        static void AllowUninstallApps(bool value);
        static bool AllowUninstallApps();
        static void AllowSetHomeConsole(bool value);
        static bool AllowSetHomeConsole();
    };
}
namespace winrt::Windows::Xbox::Safety::Internal::factory_implementation
{
    struct ConsoleSettings : ConsoleSettingsT<ConsoleSettings, implementation::ConsoleSettings>
    {
    };
}
