#pragma once
#include "Windows.Xbox.Media.SystemMediaTransportControls.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::Media::implementation
{
    struct SystemMediaTransportControls : SystemMediaTransportControlsT<SystemMediaTransportControls>
    {
        SystemMediaTransportControls() = default;

        static winrt::Windows::Xbox::Media::SystemMediaTransportControls GetForCurrentView();
        winrt::Windows::Xbox::Media::MediaPlaybackStatus PlaybackStatus();
        void PlaybackStatus(winrt::Windows::Xbox::Media::MediaPlaybackStatus const& value);
        winrt::Windows::Xbox::Media::SystemMediaTransportControlsDisplayUpdater DisplayUpdater();
        winrt::Windows::Media::SoundLevel SoundLevel();
        bool IsEnabled();
        void IsEnabled(bool value);
        bool IsPlayEnabled();
        void IsPlayEnabled(bool value);
        bool IsStopEnabled();
        void IsStopEnabled(bool value);
        bool IsPauseEnabled();
        void IsPauseEnabled(bool value);
        bool IsRecordEnabled();
        void IsRecordEnabled(bool value);
        bool IsFastForwardEnabled();
        void IsFastForwardEnabled(bool value);
        bool IsRewindEnabled();
        void IsRewindEnabled(bool value);
        bool IsPreviousEnabled();
        void IsPreviousEnabled(bool value);
        bool IsNextEnabled();
        void IsNextEnabled(bool value);
        bool IsChannelUpEnabled();
        void IsChannelUpEnabled(bool value);
        bool IsChannelDownEnabled();
        void IsChannelDownEnabled(bool value);
        bool IsBackEnabled();
        void IsBackEnabled(bool value);
        bool IsViewEnabled();
        void IsViewEnabled(bool value);
        bool IsMenuEnabled();
        void IsMenuEnabled(bool value);
        winrt::event_token ButtonPressed(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Media::SystemMediaTransportControls, winrt::Windows::Xbox::Media::SystemMediaTransportControlsButtonPressedEventArgs> const& handler);
        void ButtonPressed(winrt::event_token const& token) noexcept;
        winrt::event_token PropertyChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Media::SystemMediaTransportControls, winrt::Windows::Xbox::Media::SystemMediaTransportControlsPropertyChangedEventArgs> const& handler);
        void PropertyChanged(winrt::event_token const& token) noexcept;
    };
}
namespace winrt::Windows::Xbox::Media::factory_implementation
{
    struct SystemMediaTransportControls : SystemMediaTransportControlsT<SystemMediaTransportControls, implementation::SystemMediaTransportControls>
    {
    };
}
