#include "pch.h"
#include "Windows.Xbox.Management.Package.ContentPackageManager.h"
#include "Windows.Xbox.Management.Package.ContentPackageManager.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::Management::Package::implementation
{
    winrt::Windows::Xbox::Management::Package::ContentPackageManager ContentPackageManager::GetForProductIds(array_view<winrt::guid const> productIds)
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Xbox::Management::Package::IContentPackage> ContentPackageManager::FindPackages(winrt::Windows::Xbox::Management::Package::InstalledPackagesFilter const& filter)
    {
        throw hresult_not_implemented();
    }
    winrt::event_token ContentPackageManager::ContentPackageInstallCompleted(winrt::Windows::Xbox::Management::Package::ContentPackageInstallCompletedEventHandler const& handler)
    {
        throw hresult_not_implemented();
    }
    void ContentPackageManager::ContentPackageInstallCompleted(winrt::event_token const& token) noexcept
    {
        throw hresult_not_implemented();
    }
    winrt::event_token ContentPackageManager::ContentPackageInstallCompletedWithDetails(winrt::Windows::Foundation::EventHandler<winrt::Windows::Xbox::Management::Package::IContentPackageInstallCompletedEventArgs> const& handler)
    {
        throw hresult_not_implemented();
    }
    void ContentPackageManager::ContentPackageInstallCompletedWithDetails(winrt::event_token const& token) noexcept
    {
        throw hresult_not_implemented();
    }
}
