#include "pch.h"
#include "Windows.Xbox.Multiplayer.Internal.PartyChatAudioFocusCoordinator.h"
#include "Windows.Xbox.Multiplayer.Internal.PartyChatAudioFocusCoordinator.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::Multiplayer::Internal::implementation
{
    bool PartyChatAudioFocusCoordinator::IsSkypeOn()
    {
        throw hresult_not_implemented();
    }
    bool PartyChatAudioFocusCoordinator::IsVoiceMessagingOn()
    {
        throw hresult_not_implemented();
    }
    bool PartyChatAudioFocusCoordinator::IsPartyChatSuppressed()
    {
        throw hresult_not_implemented();
    }
    bool PartyChatAudioFocusCoordinator::IsPartyChatActive()
    {
        throw hresult_not_implemented();
    }
    void PartyChatAudioFocusCoordinator::IsSkypeOn(bool value)
    {
        throw hresult_not_implemented();
    }
    void PartyChatAudioFocusCoordinator::IsVoiceMessagingOn(bool value)
    {
        throw hresult_not_implemented();
    }
    void PartyChatAudioFocusCoordinator::IsPartyChatSuppressed(bool value)
    {
        throw hresult_not_implemented();
    }
    void PartyChatAudioFocusCoordinator::IsPartyChatActive(bool value)
    {
        throw hresult_not_implemented();
    }
    winrt::event_token PartyChatAudioFocusCoordinator::IsSkypeOnChanged(winrt::Windows::Foundation::EventHandler<bool> const& handler)
    {
        throw hresult_not_implemented();
    }
    winrt::event_token PartyChatAudioFocusCoordinator::IsVoiceMessagingOnChanged(winrt::Windows::Foundation::EventHandler<bool> const& handler)
    {
        throw hresult_not_implemented();
    }
    winrt::event_token PartyChatAudioFocusCoordinator::IsPartyChatSuppressedChanged(winrt::Windows::Foundation::EventHandler<bool> const& handler)
    {
        throw hresult_not_implemented();
    }
    winrt::event_token PartyChatAudioFocusCoordinator::IsPartyChatActiveChanged(winrt::Windows::Foundation::EventHandler<bool> const& handler)
    {
        throw hresult_not_implemented();
    }
    winrt::event_token PartyChatAudioFocusCoordinator::PartyChatCanGetAudioFocus(winrt::Windows::Foundation::EventHandler<bool> const& handler)
    {
        throw hresult_not_implemented();
    }
    void PartyChatAudioFocusCoordinator::IsSkypeOnChanged(winrt::event_token const& token) noexcept
    {
        throw hresult_not_implemented();
    }
    void PartyChatAudioFocusCoordinator::IsVoiceMessagingOnChanged(winrt::event_token const& token) noexcept
    {
        throw hresult_not_implemented();
    }
    void PartyChatAudioFocusCoordinator::IsPartyChatSuppressedChanged(winrt::event_token const& token) noexcept
    {
        throw hresult_not_implemented();
    }
    void PartyChatAudioFocusCoordinator::IsPartyChatActiveChanged(winrt::event_token const& token) noexcept
    {
        throw hresult_not_implemented();
    }
    void PartyChatAudioFocusCoordinator::PartyChatCanGetAudioFocus(winrt::event_token const& token) noexcept
    {
        throw hresult_not_implemented();
    }
    void PartyChatAudioFocusCoordinator::SetPartyAppPID(uint32_t pid)
    {
        throw hresult_not_implemented();
    }
    bool PartyChatAudioFocusCoordinator::ConsoleXCloudPlayerCanGetAudioFocus()
    {
        throw hresult_not_implemented();
    }
    winrt::event_token PartyChatAudioFocusCoordinator::ConsoleXCloudPlayerCanGetAudioFocusChanged(winrt::Windows::Foundation::EventHandler<bool> const& handler)
    {
        throw hresult_not_implemented();
    }
    void PartyChatAudioFocusCoordinator::ConsoleXCloudPlayerCanGetAudioFocusChanged(winrt::event_token const& token) noexcept
    {
        throw hresult_not_implemented();
    }
}
