#include "pch.h"
#include "Windows.Xbox.Media.SystemMediaTransportControlsDisplayUpdater.h"
#include "Windows.Xbox.Media.SystemMediaTransportControlsDisplayUpdater.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::Media::implementation
{
    winrt::Windows::Xbox::Media::MediaPlaybackType SystemMediaTransportControlsDisplayUpdater::Type()
    {
        throw hresult_not_implemented();
    }
    void SystemMediaTransportControlsDisplayUpdater::Type(winrt::Windows::Xbox::Media::MediaPlaybackType const& value)
    {
        throw hresult_not_implemented();
    }
    hstring SystemMediaTransportControlsDisplayUpdater::AppMediaId()
    {
        throw hresult_not_implemented();
    }
    void SystemMediaTransportControlsDisplayUpdater::AppMediaId(hstring const& value)
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Storage::Streams::RandomAccessStreamReference SystemMediaTransportControlsDisplayUpdater::Thumbnail()
    {
        throw hresult_not_implemented();
    }
    void SystemMediaTransportControlsDisplayUpdater::Thumbnail(winrt::Windows::Storage::Streams::RandomAccessStreamReference const& value)
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::Media::MusicDisplayProperties SystemMediaTransportControlsDisplayUpdater::MusicProperties()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::Media::VideoDisplayProperties SystemMediaTransportControlsDisplayUpdater::VideoProperties()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::Media::ImageDisplayProperties SystemMediaTransportControlsDisplayUpdater::ImageProperties()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::Media::ConversationDisplayProperties SystemMediaTransportControlsDisplayUpdater::ConversationProperties()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::Media::GameDisplayProperties SystemMediaTransportControlsDisplayUpdater::GameProperties()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::IAsyncOperation<bool> SystemMediaTransportControlsDisplayUpdater::CopyFromFileAsync(winrt::Windows::Xbox::Media::MediaPlaybackType type, winrt::Windows::Storage::StorageFile source)
    {
        throw hresult_not_implemented();
    }
    void SystemMediaTransportControlsDisplayUpdater::ClearAll()
    {
        throw hresult_not_implemented();
    }
    void SystemMediaTransportControlsDisplayUpdater::Update()
    {
        throw hresult_not_implemented();
    }
}
