#pragma once
#include "Windows.Xbox.Multiplayer.Internal.PartyChatCoordinator.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::Multiplayer::Internal::implementation
{
    struct PartyChatCoordinator
    {
        PartyChatCoordinator() = default;

        static winrt::Windows::Foundation::IAsyncAction SetAppWantsFocusAsync(bool value);
        static bool GetAppWantsFocus();
        static winrt::Windows::Foundation::IAsyncAction SetVoiceMessagingWantsFocusAsync(bool value);
        static bool GetVoiceMessagingWantsFocus();
        static winrt::event_token AppWantsFocusChanged(winrt::Windows::Foundation::EventHandler<bool> const& handler);
        static void AppWantsFocusChanged(winrt::event_token const& token) noexcept;
        static winrt::event_token VoiceMessagingWantsFocusChanged(winrt::Windows::Foundation::EventHandler<bool> const& handler);
        static void VoiceMessagingWantsFocusChanged(winrt::event_token const& token) noexcept;
    };
}
namespace winrt::Windows::Xbox::Multiplayer::Internal::factory_implementation
{
    struct PartyChatCoordinator : PartyChatCoordinatorT<PartyChatCoordinator, implementation::PartyChatCoordinator>
    {
    };
}
