#include "pch.h"
#include "Windows.Xbox.CloudLanguageServices.ConversationMessage.h"
#include "Windows.Xbox.CloudLanguageServices.ConversationMessage.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::CloudLanguageServices::implementation
{
    hstring ConversationMessage::Message()
    {
        throw hresult_not_implemented();
    }
    hstring ConversationMessage::MessageReason()
    {
        throw hresult_not_implemented();
    }
    hstring ConversationMessage::MessageText()
    {
        throw hresult_not_implemented();
    }
    hstring ConversationMessage::MessageTypeText()
    {
        throw hresult_not_implemented();
    }
    hstring ConversationMessage::MessageKnowledgeText()
    {
        throw hresult_not_implemented();
    }
    hstring ConversationMessage::DeeplinkUri()
    {
        throw hresult_not_implemented();
    }
    bool ConversationMessage::Notification()
    {
        throw hresult_not_implemented();
    }
    winrt::hresult ConversationMessage::ParseResult()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Xbox::CloudLanguageServices::DisambiguationResult> ConversationMessage::MessageDisambiguationResult()
    {
        throw hresult_not_implemented();
    }
    hstring ConversationMessage::ContractVersion()
    {
        throw hresult_not_implemented();
    }
}
