#pragma once
#include "Windows.Xbox.Multiplayer.Internal.PartyChatAudioFocusCoordinator.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::Multiplayer::Internal::implementation
{
    struct PartyChatAudioFocusCoordinator
    {
        PartyChatAudioFocusCoordinator() = default;

        static bool IsSkypeOn();
        static bool IsVoiceMessagingOn();
        static bool IsPartyChatSuppressed();
        static bool IsPartyChatActive();
        static void IsSkypeOn(bool value);
        static void IsVoiceMessagingOn(bool value);
        static void IsPartyChatSuppressed(bool value);
        static void IsPartyChatActive(bool value);
        static winrt::event_token IsSkypeOnChanged(winrt::Windows::Foundation::EventHandler<bool> const& handler);
        static winrt::event_token IsVoiceMessagingOnChanged(winrt::Windows::Foundation::EventHandler<bool> const& handler);
        static winrt::event_token IsPartyChatSuppressedChanged(winrt::Windows::Foundation::EventHandler<bool> const& handler);
        static winrt::event_token IsPartyChatActiveChanged(winrt::Windows::Foundation::EventHandler<bool> const& handler);
        static winrt::event_token PartyChatCanGetAudioFocus(winrt::Windows::Foundation::EventHandler<bool> const& handler);
        static void IsSkypeOnChanged(winrt::event_token const& token) noexcept;
        static void IsVoiceMessagingOnChanged(winrt::event_token const& token) noexcept;
        static void IsPartyChatSuppressedChanged(winrt::event_token const& token) noexcept;
        static void IsPartyChatActiveChanged(winrt::event_token const& token) noexcept;
        static void PartyChatCanGetAudioFocus(winrt::event_token const& token) noexcept;
        static void SetPartyAppPID(uint32_t pid);
        static bool ConsoleXCloudPlayerCanGetAudioFocus();
        static winrt::event_token ConsoleXCloudPlayerCanGetAudioFocusChanged(winrt::Windows::Foundation::EventHandler<bool> const& handler);
        static void ConsoleXCloudPlayerCanGetAudioFocusChanged(winrt::event_token const& token) noexcept;
    };
}
namespace winrt::Windows::Xbox::Multiplayer::Internal::factory_implementation
{
    struct PartyChatAudioFocusCoordinator : PartyChatAudioFocusCoordinatorT<PartyChatAudioFocusCoordinator, implementation::PartyChatAudioFocusCoordinator>
    {
    };
}
