#include "pch.h"
#include "Windows.Xbox.Media.SystemMediaTransportControls.h"
#include "Windows.Xbox.Media.SystemMediaTransportControls.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::Media::implementation
{
    winrt::Windows::Xbox::Media::SystemMediaTransportControls SystemMediaTransportControls::GetForCurrentView()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::Media::MediaPlaybackStatus SystemMediaTransportControls::PlaybackStatus()
    {
        throw hresult_not_implemented();
    }
    void SystemMediaTransportControls::PlaybackStatus(winrt::Windows::Xbox::Media::MediaPlaybackStatus const& value)
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::Media::SystemMediaTransportControlsDisplayUpdater SystemMediaTransportControls::DisplayUpdater()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Media::SoundLevel SystemMediaTransportControls::SoundLevel()
    {
        throw hresult_not_implemented();
    }
    bool SystemMediaTransportControls::IsEnabled()
    {
        throw hresult_not_implemented();
    }
    void SystemMediaTransportControls::IsEnabled(bool value)
    {
        throw hresult_not_implemented();
    }
    bool SystemMediaTransportControls::IsPlayEnabled()
    {
        throw hresult_not_implemented();
    }
    void SystemMediaTransportControls::IsPlayEnabled(bool value)
    {
        throw hresult_not_implemented();
    }
    bool SystemMediaTransportControls::IsStopEnabled()
    {
        throw hresult_not_implemented();
    }
    void SystemMediaTransportControls::IsStopEnabled(bool value)
    {
        throw hresult_not_implemented();
    }
    bool SystemMediaTransportControls::IsPauseEnabled()
    {
        throw hresult_not_implemented();
    }
    void SystemMediaTransportControls::IsPauseEnabled(bool value)
    {
        throw hresult_not_implemented();
    }
    bool SystemMediaTransportControls::IsRecordEnabled()
    {
        throw hresult_not_implemented();
    }
    void SystemMediaTransportControls::IsRecordEnabled(bool value)
    {
        throw hresult_not_implemented();
    }
    bool SystemMediaTransportControls::IsFastForwardEnabled()
    {
        throw hresult_not_implemented();
    }
    void SystemMediaTransportControls::IsFastForwardEnabled(bool value)
    {
        throw hresult_not_implemented();
    }
    bool SystemMediaTransportControls::IsRewindEnabled()
    {
        throw hresult_not_implemented();
    }
    void SystemMediaTransportControls::IsRewindEnabled(bool value)
    {
        throw hresult_not_implemented();
    }
    bool SystemMediaTransportControls::IsPreviousEnabled()
    {
        throw hresult_not_implemented();
    }
    void SystemMediaTransportControls::IsPreviousEnabled(bool value)
    {
        throw hresult_not_implemented();
    }
    bool SystemMediaTransportControls::IsNextEnabled()
    {
        throw hresult_not_implemented();
    }
    void SystemMediaTransportControls::IsNextEnabled(bool value)
    {
        throw hresult_not_implemented();
    }
    bool SystemMediaTransportControls::IsChannelUpEnabled()
    {
        throw hresult_not_implemented();
    }
    void SystemMediaTransportControls::IsChannelUpEnabled(bool value)
    {
        throw hresult_not_implemented();
    }
    bool SystemMediaTransportControls::IsChannelDownEnabled()
    {
        throw hresult_not_implemented();
    }
    void SystemMediaTransportControls::IsChannelDownEnabled(bool value)
    {
        throw hresult_not_implemented();
    }
    bool SystemMediaTransportControls::IsBackEnabled()
    {
        throw hresult_not_implemented();
    }
    void SystemMediaTransportControls::IsBackEnabled(bool value)
    {
        throw hresult_not_implemented();
    }
    bool SystemMediaTransportControls::IsViewEnabled()
    {
        throw hresult_not_implemented();
    }
    void SystemMediaTransportControls::IsViewEnabled(bool value)
    {
        throw hresult_not_implemented();
    }
    bool SystemMediaTransportControls::IsMenuEnabled()
    {
        throw hresult_not_implemented();
    }
    void SystemMediaTransportControls::IsMenuEnabled(bool value)
    {
        throw hresult_not_implemented();
    }
    winrt::event_token SystemMediaTransportControls::ButtonPressed(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Media::SystemMediaTransportControls, winrt::Windows::Xbox::Media::SystemMediaTransportControlsButtonPressedEventArgs> const& handler)
    {
        throw hresult_not_implemented();
    }
    void SystemMediaTransportControls::ButtonPressed(winrt::event_token const& token) noexcept
    {
        throw hresult_not_implemented();
    }
    winrt::event_token SystemMediaTransportControls::PropertyChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Media::SystemMediaTransportControls, winrt::Windows::Xbox::Media::SystemMediaTransportControlsPropertyChangedEventArgs> const& handler)
    {
        throw hresult_not_implemented();
    }
    void SystemMediaTransportControls::PropertyChanged(winrt::event_token const& token) noexcept
    {
        throw hresult_not_implemented();
    }
}
