#pragma once
#include "Windows.Xbox.Management.Devices.OpticalDrive.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::Management::Devices::implementation
{
    struct OpticalDrive : OpticalDriveT<OpticalDrive>
    {
        OpticalDrive() = default;

        winrt::event_token MediaArrived(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Management::Devices::OpticalDrive, winrt::Windows::Xbox::Management::Devices::OpticalDriveMediaChangedEventArgs> const& handler);
        void MediaArrived(winrt::event_token const& cookie) noexcept;
        winrt::event_token MediaRemoved(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Management::Devices::OpticalDrive, winrt::Windows::Xbox::Management::Devices::OpticalDriveMediaChangedEventArgs> const& handler);
        void MediaRemoved(winrt::event_token const& cookie) noexcept;
        winrt::Windows::Xbox::Management::Devices::OpticalMediaType MediaType();
        winrt::Windows::Xbox::Management::Devices::DetectedContentTypes ContentDetected();
        void SuppressAutoPlay(winrt::Windows::Xbox::Management::Devices::DetectedContentTypes const& value);
        void ResumeAutoPlay();
    };
}
namespace winrt::Windows::Xbox::Management::Devices::factory_implementation
{
    struct OpticalDrive : OpticalDriveT<OpticalDrive, implementation::OpticalDrive>
    {
    };
}
