#pragma once
#include "Windows.Xbox.Audio.BackgroundNowPlayingSession.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::Audio::implementation
{
    struct BackgroundNowPlayingSession : BackgroundNowPlayingSessionT<BackgroundNowPlayingSession>
    {
        BackgroundNowPlayingSession() = default;

        void NotifyPlaybackInfoChanged(winrt::Windows::Foundation::IInspectable const& dataSource);
        void NotifyMediaInfoChanged(winrt::Windows::Foundation::IInspectable const& dataSource);
        winrt::event_token SessionChanged(winrt::Windows::Xbox::Audio::SessionChangedEventHandler const& handler);
        void SessionChanged(winrt::event_token const& token) noexcept;
        winrt::event_token MediaChanged(winrt::Windows::Xbox::Audio::MediaChangedEventHandler const& handler);
        void MediaChanged(winrt::event_token const& token) noexcept;
        winrt::event_token PlaybackStateChanged(winrt::Windows::Xbox::Audio::PlaybackStateChangedEventHandler const& handler);
        void PlaybackStateChanged(winrt::event_token const& token) noexcept;
        winrt::Windows::Xbox::Audio::BackgroundNowPlayingSessionType CurrentSessionType();
        hstring Title();
        hstring Subtitle();
        winrt::Windows::Storage::Streams::IRandomAccessStream ThumbnailStream();
        hstring Aumid();
        hstring PrimaryPackageAumid();
        bool IsPlaying();
        bool IsShuffled();
        winrt::Windows::Xbox::Audio::BackgroundNowPlayingSessionRepeatMode RepeatMode();
        bool CanPlay();
        bool CanPause();
        bool CanSkipNext();
        bool CanSkipPrevious();
        bool CanToggleRepeat();
        bool CanToggleShuffle();
        void Play();
        void Pause();
        void SkipNext();
        void SkipPrevious();
        void ToggleRepeat();
        void ToggleShuffle();
        void Suspend();
        void Resume();
    };
}
namespace winrt::Windows::Xbox::Audio::factory_implementation
{
    struct BackgroundNowPlayingSession : BackgroundNowPlayingSessionT<BackgroundNowPlayingSession, implementation::BackgroundNowPlayingSession>
    {
    };
}
