#include "pch.h"
#include "Windows.Xbox.Graphics.Display.Internal.DisplayConfigurationInternal.h"
#include "Windows.Xbox.Graphics.Display.Internal.DisplayConfigurationInternal.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::Graphics::Display::Internal::implementation
{
    winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Xbox::Graphics::Display::Internal::AdvancedGraphicsInfo> DisplayConfigurationInternal::TrySetHdrModeAsync()
    {
        throw hresult_not_implemented();
    }
    bool DisplayConfigurationInternal::GetHdrUpconversionEnabled()
    {
        throw hresult_not_implemented();
    }
    void DisplayConfigurationInternal::SetHdrUpconversionEnabled(bool enabled)
    {
        throw hresult_not_implemented();
    }
    void DisplayConfigurationInternal::GetVariableRefreshRate(float& rateMin, float& rateMax)
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Xbox::Graphics::Display::Internal::AdvancedGraphicsInfo> DisplayConfigurationInternal::TrySetHdrModeWithPreferenceAsync(winrt::Windows::Xbox::Graphics::Display::Internal::ModePreference modePreference)
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Xbox::Graphics::Display::Internal::AdvancedGraphicsInfo> DisplayConfigurationInternal::TrySetHdrModeWithPreferenceAndMetadataAsync(winrt::Windows::Xbox::Graphics::Display::Internal::ModePreference modePreference, array_view<uint8_t const> metadata)
    {
        throw hresult_not_implemented();
    }
    void DisplayConfigurationInternal::GetDolbyVisionDisplayCapabilities(uint32_t& version, uint32_t& dmVersion, bool& parity, float& minLuminance, float& maxLuminance, float& rx, float& ry, float& gx, float& gy, float& bx, float& by, bool& enabled)
    {
        throw hresult_not_implemented();
    }
    bool DisplayConfigurationInternal::GetVrrEnabled()
    {
        throw hresult_not_implemented();
    }
}
