#pragma once
#include "Windows.Xbox.Input.GamepadReading.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::Input::implementation
{
    struct GamepadReading : GamepadReadingT<GamepadReading>
    {
        GamepadReading() = default;

        winrt::Windows::Foundation::DateTime Timestamp();
        winrt::Windows::Xbox::Input::GamepadButtons Buttons();
        bool IsDPadUpPressed();
        bool IsDPadDownPressed();
        bool IsDPadLeftPressed();
        bool IsDPadRightPressed();
        bool IsMenuPressed();
        bool IsViewPressed();
        bool IsLeftThumbstickPressed();
        bool IsRightThumbstickPressed();
        bool IsLeftShoulderPressed();
        bool IsRightShoulderPressed();
        bool IsAPressed();
        bool IsBPressed();
        bool IsXPressed();
        bool IsYPressed();
        float LeftTrigger();
        float RightTrigger();
        float LeftThumbstickX();
        float LeftThumbstickY();
        float RightThumbstickX();
        float RightThumbstickY();
        bool IsPaddle1Pressed();
        bool IsPaddle2Pressed();
        bool IsPaddle3Pressed();
        bool IsPaddle4Pressed();
    };
}
